; Imports for para boss

	.include "custom/para_boss/enumerations.asm"
	.include "custom/para_boss/update.asm"
	.include "custom/para_boss/draw.asm"
	.include "custom/para_boss/action_flutter_down.asm"
	.include "custom/para_boss/action_summon_micro_goomba.asm"
	.include "custom/para_boss/action_do_nothing.asm"
	.include "custom/para_boss/action_hover_over_player.asm"
	.include "custom/para_boss/summon_micro_goomba.asm"
	.include "custom/para_boss/hit_test.asm"
	.include "custom/para_boss/handle_horizontal_velocity.asm"
	.include "custom/para_boss/handle_vertical_velocity.asm"
	.include "custom/para_boss/apply_velocity.asm"
	.include "custom/para_boss/action_prep_attack.asm"
	.include "custom/para_boss/action_prep_long_attack.asm"
	.include "custom/para_boss/action_be_slow.asm"
	.include "custom/para_boss/action_prep_short_attack.asm"
	.include "custom/para_boss/action_summon_goomba.asm"
	.include "custom/core/generator/prepare_new_goomba.asm"
	.include "custom/core/generator/prepare_new_object.asm"
	.include "custom/core/generator/prepare_new_object_or_abort.asm"
	.include "custom/para_boss/action_determine_attack.asm"
	.include "custom/para_boss/hit_interrupt.asm"
	.include "custom/para_boss/action_get_hit.asm"
	.include "custom/para_boss/action_prep_get_hit.asm"
	.include "custom/para_boss/action_determine_flight.asm"